site_name: Golem Network Docs
nav:
    - Home: 'index.md'
    - 'Create on Golem':
      - 'creators/index.md'
      - JavaScript:
          - 'creators/javascript/index.md'
          - Quickstart: 'creators/javascript/quickstart.md'
          - 'High Level API':
            - 'creators/javascript/high-level/index.md'
            - 'Task Model': 'creators/javascript/high-level/task-model.md'
            - Examples:
                - '#0 - Hello World': 'creators/javascript/high-level/examples/hello.md'
                - '#1 - Simple Usage': 'creators/javascript/high-level/examples/simple.md'
                - '#2 - Hashcat on Golem': 'creators/javascript/high-level/examples/hashcat.md'
                - '#3 - Requestor in browser': 'creators/javascript/high-level/examples/web.md'
          - 'Mid Level API':
            - 'creators/javascript/mid-level/index.md'
            - Examples:
                - '#0 - Hello World': 'creators/javascript/mid-level/examples/hello.md'
                - '#1 - Requestor in browser': 'creators/javascript/mid-level/examples/web.md'
          - 'API Reference': 'creators/javascript/docs/index.md'
      - Python:
          - 'creators/python/index.md'
      - 'No-code':
          - 'creators/dapps/index.md'
    - 'Earn on Golem': 'providers/index.md'
    - 'What is Golem': 'architecture/index.md'
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
repo_url: https://github.com/golemfactory/golem-docs
copyright: >
  Copyright &copy; 2023 Golem Network –
  <a href="#__consent">Change cookie settings</a>
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/golemfactory
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/golem-network
    - icon: fontawesome/brands/discord
      link: https://chat.golem.network/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-D8XHPYHYHP
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting an issue on our <a href="https://github.com/golemfactory/golem-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub repository</a>.
