name: Validate local links in the docs

on:
  pull_request: # This triggers the action on all PRs

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: node validate_links.js
